import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service.js';
import type { SecurityScanJobData } from '../constants.js';

@Injectable()
export class ObservationVerificationStage {
  private readonly logger = new Logger(ObservationVerificationStage.name);

  constructor(private readonly prisma: PrismaService) {}

  async execute(data: SecurityScanJobData): Promise<void> {
    const observations = await this.prisma.securityObservation.findMany({
      where: { scanId: data.scanId, status: 'PENDING' },
      include: {
        evidenceArtifacts: { orderBy: { createdAt: 'asc' } },
      },
      orderBy: { createdAt: 'asc' },
    });

    for (const observation of observations) {
      const labels = Array.isArray(observation.labels) ? observation.labels.map(String) : [];
      const isLabOnly = labels.includes('LAB_ONLY');
      const evidenceCount = observation.evidenceArtifacts.length;
      const deterministicProof = observation.proofType !== 'HEURISTIC';
      const hasPrimaryEvidence = evidenceCount >= 1;
      const corroborated = (deterministicProof && hasPrimaryEvidence) || evidenceCount >= 2 || labels.includes('CORROBORATED');

      if (!corroborated && !isLabOnly) {
        await this.prisma.securityObservation.update({
          where: { id: observation.id },
          data: {
            status: 'SUPPRESSED',
          },
        });
        continue;
      }

      const validationState = isLabOnly
        ? 'LAB_ONLY'
        : (deterministicProof && hasPrimaryEvidence) || evidenceCount >= 2
          ? 'VALIDATED'
          : 'PROBABLE';

      const primaryEvidence = observation.evidenceArtifacts[0] ?? null;

      await this.prisma.securityFinding.create({
        data: {
          scanId: data.scanId,
          observationId: observation.id,
          primaryEvidenceId: primaryEvidence?.id,
          category: observation.category,
          title: observation.title,
          severity: this.adjustSeverity(observation.severity, isLabOnly) as never,
          exploitability: observation.exploitability,
          confidence: this.adjustConfidence(observation.confidence, evidenceCount, deterministicProof) as never,
          validationState: validationState as never,
          endpoint: observation.endpoint,
          httpMethod: observation.httpMethod,
          parameter: observation.parameter,
          scenarioPackSlug: observation.scenarioPackSlug,
          attackFlow: {
            steps: [
              { action: 'Observation generated by scenario execution', proofType: observation.proofType },
              { action: 'Evidence verifier evaluated observation', evidenceCount },
            ],
          },
          evidence: {
            ...(observation.evidenceSummary as Record<string, unknown> | null ?? {}),
            proofType: observation.proofType,
            rawEvidenceRefs: observation.evidenceArtifacts.map((artifact) => artifact.id),
            reproduction: primaryEvidence?.summary ?? null,
            safetyNotes: isLabOnly ? 'Observation collected from a local or laboratory target.' : 'Safe validation only.',
            affectedAssets: observation.affectedAssets,
            attckTechniques: observation.attckTechniques,
          } as Prisma.InputJsonValue,
          affectedAssets: jsonOrUndefined(observation.affectedAssets),
          attckTechniques: jsonOrUndefined(observation.attckTechniques),
          labels,
          remediation: observation.remediation,
          references: jsonOrUndefined(observation.references),
          fingerprint: `${observation.category}:${observation.title}:${observation.endpoint ?? '/'}`,
        },
      });

      await this.prisma.securityObservation.update({
        where: { id: observation.id },
        data: { status: 'VERIFIED' },
      });
    }

    this.logger.log(`Observation verification completed for scan ${data.scanId}`);
  }

  private adjustSeverity(severity: string, isLabOnly: boolean) {
    if (!isLabOnly) {
      return severity;
    }

    const order = ['INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
    const current = order.indexOf(severity);
    if (current <= 0) {
      return 'INFORMATIONAL';
    }
    return order[current - 1];
  }

  private adjustConfidence(confidence: string, evidenceCount: number, deterministicProof: boolean) {
    if (evidenceCount >= 2) {
      return 'HIGH';
    }

    if (!deterministicProof && confidence === 'HIGH') {
      return 'MEDIUM';
    }

    if (confidence === 'HIGH' && evidenceCount === 0) {
      return 'MEDIUM';
    }

    return confidence;
  }
}

function jsonOrUndefined(value: Prisma.JsonValue | null): Prisma.InputJsonValue | undefined {
  return value === null ? undefined : (value as Prisma.InputJsonValue);
}
